server.port=8085
spring.application.name=java-analytics-api

# Druid SQL Broker endpoint (inside Docker network)
druid.broker.url=http://broker:8082/druid/v2/sql

# Logging
logging.level.root=INFO
logging.level.com.ai.analytics=DEBUG
